local mod = dmhub.GetModLoading()

local g_tableCache = {}
local g_empty = {}

--- BEGIN generated by tools/lua-typing/gen_table_overloads.py -- do not edit by hand
--- Typed per table like dmhub.GetTable: rows of a table a game type declares with
--- `X.tableName` come back as X.
---@overload fun(tableName: "abilityTemplates"): table<string, AbilityTemplate>
---@overload fun(tableName: "attributeGenerator"): table<string, AttributeGenerator>
---@overload fun(tableName: "audioPlaylists"): table<string, AudioPlaylist>
---@overload fun(tableName: "audioVariantPools"): table<string, VariantPool>
---@overload fun(tableName: "backgrounds"|"careers"): table<string, Background>
---@overload fun(tableName: "campaignNotes"): table<string, CampaignNote>
---@overload fun(tableName: "characterOngoingEffects"): table<string, CharacterOngoingEffect>
---@overload fun(tableName: "characterResources"): table<string, CharacterResource>
---@overload fun(tableName: "characterTypes"): table<string, CharacterType>
---@overload fun(tableName: "charConditions"): table<string, CharacterCondition>
---@overload fun(tableName: "classes"): table<string, Class>
---@overload fun(tableName: "compendiumPermissions"): table<string, CompendiumPermission>
---@overload fun(tableName: "complications"): table<string, CharacterComplication>
---@overload fun(tableName: "cultureAspects"): table<string, CultureAspect>
---@overload fun(tableName: "cultures"): table<string, Culture>
---@overload fun(tableName: "currency"): table<string, Currency>
---@overload fun(tableName: "customAttributes"): table<string, CustomAttribute>
---@overload fun(tableName: "customfields"): table<string, CustomFieldCollection>
---@overload fun(tableName: "damageFlags"): table<string, DamageFlag>
---@overload fun(tableName: "damageTypes"): table<string, DamageType>
---@overload fun(tableName: "Deities"): table<string, Deity>
---@overload fun(tableName: "DeityDomains"): table<string, DeityDomain>
---@overload fun(tableName: "documents"): table<string, CustomDocument>
---@overload fun(tableName: "downtimeActivities"): table<string, DowntimeActivity>
---@overload fun(tableName: "encounterfolders"): table<string, EncounterFolder>
---@overload fun(tableName: "encounterRuleSets"): table<string, EncounterRuleSet>
---@overload fun(tableName: "encounters"): table<string, Encounter>
---@overload fun(tableName: "encounterScripts"): table<string, EncounterScript>
---@overload fun(tableName: "environmentalKeywords"): table<string, EnvironmentalKeyword>
---@overload fun(tableName: "equipmentCategories"): table<string, EquipmentCategory>
---@overload fun(tableName: "feats"): table<string, CharacterFeat>
---@overload fun(tableName: "featurePrefabs"): table<string, CharacterFeaturePrefabs>
---@overload fun(tableName: "FishSpecies"): table<string, FishSpecies>
---@overload fun(tableName: "footprintStyles"): table<string, FootprintStyle>
---@overload fun(tableName: "glossaryTerms"): table<string, GlossaryTerm>
---@overload fun(tableName: "journalStyles"): table<string, JournalStylesheet>
---@overload fun(tableName: "kits"): table<string, Kit>
---@overload fun(tableName: "languageRelations"): table<string, LanguageRelation>
---@overload fun(tableName: "languages"): table<string, Language>
---@overload fun(tableName: "liveencounters"): table<string, LiveEncounter>
---@overload fun(tableName: "mapScripts"): table<string, MapScript>
---@overload fun(tableName: "MonsterGroup"): table<string, MonsterGroup>
---@overload fun(tableName: "negotiators"): table<string, Negotiator>
---@overload fun(tableName: "parties"): table<string, Party>
---@overload fun(tableName: "pdfReferences"): table<string, PDFFragment>
---@overload fun(tableName: "powerRolls"): table<string, PowerRollTableGroup>
---@overload fun(tableName: "proficiencyLevel"): table<string, ProficiencyLevel>
---@overload fun(tableName: "races"): table<string, Race>
---@overload fun(tableName: "Skills"): table<string, Skill>
---@overload fun(tableName: "SpellLists"): table<string, SpellList>
---@overload fun(tableName: "Spells"): table<string, Spell>
---@overload fun(tableName: "tbl_Gear"): table<string, equipment>
---@overload fun(tableName: "titles"): table<string, Title>
---@overload fun(tableName: "VisionType"): table<string, VisionType>
---@overload fun(tableName: "weaponProperties"): table<string, WeaponProperty>
---@param tableName string
---@return table<string, table>
--- END generated by tools/lua-typing/gen_table_overloads.py
function GetTableCached(tableName)
    local result = g_tableCache[tableName]
    if not result then
        result = dmhub.GetTable(tableName)
        g_tableCache[tableName] = result
    end

    return result or g_empty
end

dmhub.RegisterEventHandler("refreshTables", function(keys)
    g_tableCache = {}
end)